global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "dev_app"
    metrics_path: /metrics
    static_configs:
      - targets:
          # - "host.docker.internal:8000"
          - "localhost:8000"
